name: Blatt 2

on: [pull_request, workflow_dispatch, push]

jobs:
  checkgrammar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: apt install -y make antlr4
      - name: Run tests
        run: |
          cd Blatt\ 2
          make test
