name: Blatt 2

on: [pull_request, workflow_dispatch, push]

jobs:
  checkgrammar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: sudo apt update && sudo apt install -y make antlr4

      - name: Run tests Parser/Lexer
        run: |
          cd Blatt\ 2
          make test

      - name: Run tests AST
        run: |
          cd Blatt\ 2
          make testAST
